### ISSUE TITLE
配置多个indexs异常

### ISSUE THREAD

**Issue by shengming123** [lifengdi/search#3]
2022-01-22 17:57:43  INFO  38609 --- [nio-8085-exec-1] com.lifengdi.init.InitIndexService       : 创建Mapping映射，clazz:class com.lifengdi.document.HouseDocument
2022-01-22 17:57:43  ERROR 38999 --- [nio-8085-exec-1] com.lifengdi.init.InitIndexService       : 创建索引异常
java.lang.IllegalArgumentException: Rejecting mapping update to [house] as the final mapping would have more than 1 type: [storehouseinfo, base]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:459)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:403)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:338)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:330)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:231)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:270)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:200)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:135)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
-------------
对house进行保存index报错。String index = elasticsearchTemplate.index(indexQuery);

/index/init接口 中 elasticsearchTemplate.putMapping(clazz.newInstance().getClass())这行报错
------------------------
配置了多个doc,启动正常对storer保存index正常。
yml配置
index-entity:
  configs:
    - docCode: store
      indexName: store
      type: base
      documentPath: com.lifengdi.document.StoreDocument
      scrollTimeInMillis: 60000
    - docCode: house
      indexName: house
      type: base
      documentPath: com.lifengdi.document.HouseDocument
      scrollTimeInMillis: 60000
------------
HouseDocument 类
package com.lifengdi.document;

import com.lifengdi.document.house.HouseBaseInfo;
import com.lifengdi.search.annotation.DefinitionQuery;
import com.lifengdi.search.enums.QueryTypeEnum;
import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;

/**
 * 门店Document
 *
 * @author 李锋镝
 * @date Create at 19:31 2019/8/22
 */
@Document(indexName = "house", type = "base")
@Data
@DefinitionQuery(key = "page", type = QueryTypeEnum.IGNORE)
@DefinitionQuery(key = "size", type = QueryTypeEnum.IGNORE)
@DefinitionQuery(key = "q", type = QueryTypeEnum.FULLTEXT)
public class HouseDocument {

    @Id
    @DefinitionQuery(type = QueryTypeEnum.IN)
    @DefinitionQuery(key = "id", type = QueryTypeEnum.IN)
    @Field(type = FieldType.Keyword)
    private String id;

    /**
     * 基础信息
     */
    @Field(type = FieldType.Object)
    private HouseBaseInfo baseInfo;
}

----------
HouseBaseInfo 类
package com.lifengdi.document.house;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.lifengdi.search.annotation.DefinitionQuery;
import com.lifengdi.search.enums.QueryTypeEnum;
import com.lifengdi.serializer.JodaDateTimeDeserializer;
import com.lifengdi.serializer.JodaDateTimeSerializer;
import lombok.Data;
import org.joda.time.DateTime;
import org.springframework.data.elasticsearch.annotations.Field;
import org.springframework.data.elasticsearch.annotations.FieldType;

@Data
public class HouseBaseInfo {

    @Field(type = FieldType.Keyword)
    private String houseId;//房源编号

    @Field(type = FieldType.Text, analyzer = "ik_smart", searchAnalyzer = "ik_smart")
    @DefinitionQuery(type = QueryTypeEnum.FUZZY) //模糊
    @DefinitionQuery(key = "name", type = QueryTypeEnum.SHOULD) //或者(满足其中一个条件即可)
    private String housingName;        //房源名称

    /**
     * 创建时间
     */
    @Field(type = FieldType.Date)
    @JsonDeserialize(using = JodaDateTimeDeserializer.class)
    @JsonSerialize(using = JodaDateTimeSerializer.class)
    @DefinitionQuery(type = QueryTypeEnum.RANGE) //范围
    public DateTime createdTime;
}

----------

**Comment by shengming123** [comment]
/index/init接口报错行
![Xnip2022-01-22_18-29-38](https://user-images.githubusercontent.com/19882073/150634885-05f2cf2e-d375-4beb-8b94-abd3c244099d.png)

**Comment by shengming123** [comment]
IndexEntity configs 可以读到2项
![Xnip2022-01-23_09-32-21](https://user-images.githubusercontent.com/19882073/150661231-ddcee4d7-d700-4db8-924c-a8008484291e.png)

**Comment by shengming123** [comment]
对init方法中类的mapping做了调整。根据yml配置path来映射类，但问题仍存在
![Xnip2022-01-23_10-59-22](https://user-images.githubusercontent.com/19882073/150663070-f2c5d41b-1f0a-45f7-8469-ba1c3fb84cbc.png)

**Comment by shengming123** [comment]
已经解决，我建立的索引是旧的。删除后，重建就可以了。

**Comment by lifengdi** [comment]
ES的索引，只能增量新增，不能修改旧有的索引。
